/**
 * Vite development / production server helpers for the TonerWeb AI Assistant.
 *
 * This module exports two utility functions that integrate Vite with an Express
 * backend:
 *
 * 1. `setupVite()` – Creates an **in-memory Vite dev server** (middleware mode)
 *    and wires its middlewares into the provided Express application. Hot-module
 *    reloading (HMR) is configured to share the existing HTTP server instance
 *    so that API routes and the React client live on the same port during
 *    development.
 *
 * 2. `serveStatic()` – Serves the **pre-built** production assets from the
 *    `public` directory generated by `vite build`. It acts as a graceful
 *    fallback when the application is running in production mode where a dev
 *    server is not desirable.
 *
 * The helper also exposes a small `log()` wrapper that funnels messages through
 * the shared Winston logger, ensuring consistent log formatting across
 * server-side modules.
 *
 * @module server/vite
 * @author TonerWeb Team
 * @version 1.0.0
 * @see https://vitejs.dev/guide/ssr
 */

import express, { type Express } from "express";
import fs from "fs";
import path from "path";
import { createServer as createViteServer, createLogger } from "vite";
import { type Server } from "http";
import viteConfig from "../vite.config";
import { nanoid } from "nanoid";
import { logger } from "@shared/logger";

const viteLogger = createLogger();

export function log(message: string, source = "express") {
  const formattedTime = new Date().toLocaleTimeString("en-US", {
    hour: "numeric",
    minute: "2-digit",
    second: "2-digit",
    hour12: true,
  });

  logger.info(`[${source}] ${message}`);
}

export async function setupVite(app: Express, server: Server) {
  const serverOptions = {
    middlewareMode: true,
    hmr: { server },
    allowedHosts: true as const,
  };

  const vite = await createViteServer({
    ...viteConfig,
    configFile: false,
    customLogger: {
      ...viteLogger,
      error: (msg, options) => {
        viteLogger.error(msg, options);
        process.exit(1);
      },
    },
    server: serverOptions,
    appType: "custom",
  });

  app.use(vite.middlewares);
  app.use("*", async (req, res, next) => {
    const url = req.originalUrl;

    try {
      const clientTemplate = path.resolve(
        import.meta.dirname,
        "..",
        "client",
        "index.html",
      );

      // always reload the index.html file from disk incase it changes
      let template = await fs.promises.readFile(clientTemplate, "utf-8");
      template = template.replace(
        `src="/src/main.tsx"`,
        `src="/src/main.tsx?v=${nanoid()}"`,
      );
      const page = await vite.transformIndexHtml(url, template);
      res.status(200).set({ "Content-Type": "text/html" }).end(page);
    } catch (e) {
      vite.ssrFixStacktrace(e as Error);
      next(e);
    }
  });
}

export function serveStatic(app: Express) {
  const distPath = path.resolve(import.meta.dirname, "public");

  if (!fs.existsSync(distPath)) {
    throw new Error(
      `Could not find the build directory: ${distPath}, make sure to build the client first`,
    );
  }

  app.use(express.static(distPath));

  // fall through to index.html if the file doesn't exist
  app.use("*", (_req, res) => {
    res.sendFile(path.resolve(distPath, "index.html"));
  });
}
